language: ruby
rvm:
  - 2.3.0

before_script:
  - chmod +x ./_script/cibuild
  - npm install --global surge

script: ./_script/cibuild

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false 

after_success:
   surge -d https://gmmiw2016.surge.sh -p ./_site/
