# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Graduate Math Modelling in Industry - 2016
tagline:             'Discovery of Mathematical Sciences'
description: >
  The GMMIW (Graduate Mathematical Modelling in Industry Workshop) is a week
  long workshop which brings together Graduate Students and Industry Experts to
  work on real world problems.

url:                 http://gmmiw2016.surge.sh
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Conference Organizer
  url:               https://twitter.com/pimsmath
  email:             info@pims.math.ca

exclude: [ 'package.json','Gemfile','_script','vendor']
