# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
gems: [jekyll-paginate]

# Setup
title:               Graduate Math Modelling in Industry - 2016
#tagline:             'A Jekyll theme'
description: >
  The GMMIW (Graduate Mathematical Modelling in Industry Workshop) is a week
  long workshop which brings together Graduate Students and Industry Experts to
  work on real world problems.

url:                 http://gmmiw2016.surge.sh
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

exclude: [ 'package.json','Gemfile','_script','vendor']
