# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true
# gems: [jekyll-paginate]

# Setup
title:               GMMIW2016
tagline:             'Graduate Mathematical Modeling in Industry'
description: >
  The GMMIW (Graduate Mathematical Modelling in Industry Workshop) is a week
  long workshop which brings together Graduate Students and Industry Experts to
  work on real world problems.

url:                 http://gmmiw2016.surge.sh
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Conference Organizer
  url:               https://twitter.com/pimsmath
  email:             info@pims.math.ca

exclude: [ 'package.json','Gemfile','_script','vendor']

gems:
  - jekyll-gist
  - jekyll-paginate